### ISSUE TITLE
Tapping this app's icon and the app crashes

### ISSUE THREAD

**Issue by whitedavidp** [ProjectUNBI/TCPserver_TASKER_plugin#1]
On Android 9 this app just crashes when the home screen icon is tapped. From logcat:

[07-24 12:38:28.768 16660:16660 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: com.unbi.tcpserver, PID: 16660
android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 backgroundColor=0x00000000 vis=PRIVATE)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1782)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:205)
	at android.app.ActivityThread.main(ActivityThread.java:6983)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)

**Comment by whitedavidp** [comment]
Oh, I now see there is a different app for Oreo+. Sorry
